### ISSUE TITLE
Support for Kubernetes Cluster

### ISSUE THREAD

**Issue by iramsey85** [hypriot/rpi-docker-builder#16]
I've been using the Hypriot image along with the Kubernetes Up and Running book to build a Kubernetes Raspberry Pi cluster. The book suggests setting up NAT on the worker nodes. I'm assuming they would access the internet throguh the master node, which is server DHCP addresses. 

Is that a recommended implementation or would you suggest enabling Internet access on each raspberry-pi through the onboard wifi?

**Comment by firecyberice** [comment]
Closing because it is not related to this repo.

**Comment by StefanScherer** [comment]
Maybe you find more people with Kubernetes knowledge in our gitter channel https://gitter.im/hypriot/talk
